packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  esbuild: false
  sharp: false

minimumReleaseAgeExclude:
  - '@tuwaio/*'
  - viem
  - '@tailwindcss/*'
  - '@typescript-eslint/*'
  - prettier
  - tailwindcss
  - typescript-eslint
  - eslint@10.8.1
